version: "3.7"

services:
  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PROJECT_PATH=${APP_CODE_PATH_HOST}
        - NODE_ENV=${NODE_ENV}
        - YARN=${YARN_INSTALL}
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    tty: true

  nginx:
    build:
      context: ./nginx
    working_dir: ${APP_CODE_PATH_CONTAINER}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./nginx/sites:/etc/nginx/sites-available

  caddy:
    build:
      context: ./caddy
    working_dir: ${APP_CODE_PATH_CONTAINER}
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./caddy/sites/Caddyfile:/etc/Caddyfile
      - ./caddy/logs:/var/log/caddy
    depends_on:
      - node

  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    ports:
      - "${MYSQL_PORT}:3306"

  adminer:
    build:
      context: ./adminer
    ports:
      - 8080:8080

  gitlab-runner:
    build:
      context: ./gitlab-runner
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:/home/gitlab-runner/www
      - ./gitlab-runner/conf:/etc/gitlab-runner
      - ./gitlab-runner/conf/docker.sock:/var/run/docker.sock

  openproject:
    build:
      context: ./openproject
    # links:
    #   - mysql
    environment:
      - SECRET_KEY_BASE=${OPENPROJECT_SECRET_KEY}
      # - DATABASE_URL=mysql2://default:secret@localhost:3306/openproject
    volumes:
      - ${DATA_PATH_HOST}/openproject/pgdata:/var/openproject/pgdata
      - ${DATA_PATH_HOST}/openproject/static:/var/openproject/assets
      # - ./openproject/config:/var/config
    ports:
      - 8888:8080
